# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Push a new beta build to Firebase App Distribution"
  lane :beta do
    gradle(task: 'assemble', build_type: 'Release')
    firebase_app_distribution(
      app: "1:983164358479:android:eb922c5ff359ccc5e5ff3a",
      groups: "all",
      release_notes: "Lots of amazing new features to test out!",
      firebase_cli_path: `which firebase`.strip(),
      apk_path: "../build/app/outputs/apk/release/app-release.apk"
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
