name: Deploy to App Distribution

on: [push]

jobs:
  build:

    runs-on: macOS-10.14
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: subosito/flutter-action@v1.1.1
      with:
        channel: 'stable' # or: 'dev' or 'beta'
    - name: Deploy to Firebase App Distribution
      run: |
        npm install -g firebase-tools
        gem install bundler:1.17.2
        sudo xcode-select -s /Applications/Xcode_11.app
        flutter build ios --release --no-codesign
        flutter build android
      working-directory: ./
    - name: iOS
      run: |
        bundle install
        bundle exec fastlane app_distribution
      working-directory: ./ios
      env:
        PERSONAL_ACCESS_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }} # In case of using match
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }} # In case of using match
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - name: Android
      run: |
        bundle install
        bundle exec fastlane beta
      working-directory: ./android
      env:
        PERSONAL_ACCESS_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }} # In case of using match
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }} # In case of using match
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
